/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Category } from "./category";
import { CategoryObject } from "./categoryobject";
import { IdName } from "./idname";
import { SiteObject } from "./siteobject";
import { Expose, Type } from "class-transformer";

export enum MobileDeviceConfigurationProfileGeneralDeploymentMethod {
    InstallAutomatically = "Install Automatically",
    MakeAvailableInSelfService = "Make Available in Self Service",
}

/**
 * Level of the configuration profile
 */
export enum MobileDeviceConfigurationProfileGeneralLevel {
    System = "System",
    User = "User",
}

export class MobileDeviceConfigurationProfileGeneral extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "category" })
    @Type(() => CategoryObject)
    category?: CategoryObject;

    @SpeakeasyMetadata()
    @Expose({ name: "deployment_method" })
    deploymentMethod?: MobileDeviceConfigurationProfileGeneralDeploymentMethod;

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Level of the configuration profile
     */
    @SpeakeasyMetadata()
    @Expose({ name: "level" })
    level?: MobileDeviceConfigurationProfileGeneralLevel;

    /**
     * Name of the configuration profile
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "payloads" })
    payloads?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "redeploy_Dayss_before_certificate_expires" })
    redeployDayssBeforeCertificateExpires?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "redeploy_on_update" })
    redeployOnUpdate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "site" })
    @Type(() => SiteObject)
    site?: SiteObject;

    @SpeakeasyMetadata()
    @Expose({ name: "uuid" })
    uuid?: string;
}

export class MobileDeviceConfigurationProfileScopeBuildings extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "building" })
    @Type(() => IdName)
    building?: IdName;
}

export class MobileDeviceConfigurationProfileScopeDepartments extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "department" })
    @Type(() => IdName)
    department?: IdName;
}

export class MobileDeviceConfigurationProfileScopeExclusionsBuildings extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "building" })
    @Type(() => IdName)
    building?: IdName;
}

export class MobileDeviceConfigurationProfileScopeExclusionsDepartments extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "department" })
    @Type(() => IdName)
    department?: IdName;
}

export class MobileDeviceConfigurationProfileScopeExclusionsIbeacons extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "ibeacon" })
    @Type(() => IdName)
    ibeacon?: IdName;
}

export class MobileDeviceConfigurationProfileScopeExclusionsJssUserGroups extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user_group" })
    @Type(() => IdName)
    userGroup?: IdName;
}

export class MobileDeviceConfigurationProfileScopeExclusionsJssUsers extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user" })
    @Type(() => IdName)
    user?: IdName;
}

export class MobileDeviceConfigurationProfileScopeExclusionsMobileDeviceGroups extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "mobile_device_group" })
    @Type(() => IdName)
    mobileDeviceGroup?: IdName;
}

export class MobileDeviceConfigurationProfileScopeExclusionsMobileDevicesMobileDevice extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Name of the device
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "udid" })
    udid?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "wifi_mac_address" })
    wifiMacAddress?: string;
}

export class MobileDeviceConfigurationProfileScopeExclusionsMobileDevices extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "mobile_device" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsMobileDevicesMobileDevice)
    mobileDevice?: MobileDeviceConfigurationProfileScopeExclusionsMobileDevicesMobileDevice;
}

export class MobileDeviceConfigurationProfileScopeExclusionsNetworkSegmentsNetworkSegment extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Name of the network segment
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "uid" })
    uid?: string;
}

export class MobileDeviceConfigurationProfileScopeExclusionsNetworkSegments extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "network_segment" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsNetworkSegmentsNetworkSegment)
    networkSegment?: MobileDeviceConfigurationProfileScopeExclusionsNetworkSegmentsNetworkSegment;
}

export class MobileDeviceConfigurationProfileScopeExclusionsUserGroups extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user_group" })
    @Type(() => IdName)
    userGroup?: IdName;
}

export class MobileDeviceConfigurationProfileScopeExclusionsUsersUser extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class MobileDeviceConfigurationProfileScopeExclusionsUsers extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsUsersUser)
    user?: MobileDeviceConfigurationProfileScopeExclusionsUsersUser;
}

export class MobileDeviceConfigurationProfileScopeExclusions extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeExclusionsBuildings })
    @Expose({ name: "buildings" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsBuildings)
    buildings?: MobileDeviceConfigurationProfileScopeExclusionsBuildings[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeExclusionsDepartments })
    @Expose({ name: "departments" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsDepartments)
    departments?: MobileDeviceConfigurationProfileScopeExclusionsDepartments[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeExclusionsIbeacons })
    @Expose({ name: "ibeacons" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsIbeacons)
    ibeacons?: MobileDeviceConfigurationProfileScopeExclusionsIbeacons[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeExclusionsJssUserGroups })
    @Expose({ name: "jss_user_groups" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsJssUserGroups)
    jssUserGroups?: MobileDeviceConfigurationProfileScopeExclusionsJssUserGroups[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeExclusionsJssUsers })
    @Expose({ name: "jss_users" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsJssUsers)
    jssUsers?: MobileDeviceConfigurationProfileScopeExclusionsJssUsers[];

    @SpeakeasyMetadata({
        elemType: MobileDeviceConfigurationProfileScopeExclusionsMobileDeviceGroups,
    })
    @Expose({ name: "mobile_device_groups" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsMobileDeviceGroups)
    mobileDeviceGroups?: MobileDeviceConfigurationProfileScopeExclusionsMobileDeviceGroups[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeExclusionsMobileDevices })
    @Expose({ name: "mobile_devices" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsMobileDevices)
    mobileDevices?: MobileDeviceConfigurationProfileScopeExclusionsMobileDevices[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeExclusionsNetworkSegments })
    @Expose({ name: "network_segments" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsNetworkSegments)
    networkSegments?: MobileDeviceConfigurationProfileScopeExclusionsNetworkSegments[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeExclusionsUserGroups })
    @Expose({ name: "user_groups" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsUserGroups)
    userGroups?: MobileDeviceConfigurationProfileScopeExclusionsUserGroups[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeExclusionsUsers })
    @Expose({ name: "users" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusionsUsers)
    users?: MobileDeviceConfigurationProfileScopeExclusionsUsers[];
}

export class MobileDeviceConfigurationProfileScopeJssUserGroups extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user_group" })
    @Type(() => IdName)
    userGroup?: IdName;
}

export class MobileDeviceConfigurationProfileScopeJssUsers extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user" })
    @Type(() => IdName)
    user?: IdName;
}

export class MobileDeviceConfigurationProfileScopeLimitationsIbeacons extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "ibeacon" })
    @Type(() => IdName)
    ibeacon?: IdName;
}

export class MobileDeviceConfigurationProfileScopeLimitationsNetworkSegments extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "network_segment" })
    @Type(() => IdName)
    networkSegment?: IdName;
}

export class MobileDeviceConfigurationProfileScopeLimitationsUserGroups extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user_group" })
    @Type(() => IdName)
    userGroup?: IdName;
}

export class MobileDeviceConfigurationProfileScopeLimitationsUsers extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user" })
    @Type(() => IdName)
    user?: IdName;
}

export class MobileDeviceConfigurationProfileScopeLimitations extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeLimitationsIbeacons })
    @Expose({ name: "ibeacons" })
    @Type(() => MobileDeviceConfigurationProfileScopeLimitationsIbeacons)
    ibeacons?: MobileDeviceConfigurationProfileScopeLimitationsIbeacons[];

    @SpeakeasyMetadata({
        elemType: MobileDeviceConfigurationProfileScopeLimitationsNetworkSegments,
    })
    @Expose({ name: "network_segments" })
    @Type(() => MobileDeviceConfigurationProfileScopeLimitationsNetworkSegments)
    networkSegments?: MobileDeviceConfigurationProfileScopeLimitationsNetworkSegments[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeLimitationsUserGroups })
    @Expose({ name: "user_groups" })
    @Type(() => MobileDeviceConfigurationProfileScopeLimitationsUserGroups)
    userGroups?: MobileDeviceConfigurationProfileScopeLimitationsUserGroups[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeLimitationsUsers })
    @Expose({ name: "users" })
    @Type(() => MobileDeviceConfigurationProfileScopeLimitationsUsers)
    users?: MobileDeviceConfigurationProfileScopeLimitationsUsers[];
}

export class MobileDeviceConfigurationProfileScopeMobileDeviceGroups extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "mobile_device_group" })
    @Type(() => IdName)
    mobileDeviceGroup?: IdName;
}

export class MobileDeviceConfigurationProfileScopeMobileDevicesMobileDevice extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Name of the device
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "udid" })
    udid?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "wifi_mac_address" })
    wifiMacAddress?: string;
}

export class MobileDeviceConfigurationProfileScopeMobileDevices extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "mobile_device" })
    @Type(() => MobileDeviceConfigurationProfileScopeMobileDevicesMobileDevice)
    mobileDevice?: MobileDeviceConfigurationProfileScopeMobileDevicesMobileDevice;
}

export class MobileDeviceConfigurationProfileScope extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "all_jss_users" })
    allJssUsers?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "all_mobile_devices" })
    allMobileDevices?: boolean;

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeBuildings })
    @Expose({ name: "buildings" })
    @Type(() => MobileDeviceConfigurationProfileScopeBuildings)
    buildings?: MobileDeviceConfigurationProfileScopeBuildings[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeDepartments })
    @Expose({ name: "departments" })
    @Type(() => MobileDeviceConfigurationProfileScopeDepartments)
    departments?: MobileDeviceConfigurationProfileScopeDepartments[];

    @SpeakeasyMetadata()
    @Expose({ name: "exclusions" })
    @Type(() => MobileDeviceConfigurationProfileScopeExclusions)
    exclusions?: MobileDeviceConfigurationProfileScopeExclusions;

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeJssUserGroups })
    @Expose({ name: "jss_user_groups" })
    @Type(() => MobileDeviceConfigurationProfileScopeJssUserGroups)
    jssUserGroups?: MobileDeviceConfigurationProfileScopeJssUserGroups[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeJssUsers })
    @Expose({ name: "jss_users" })
    @Type(() => MobileDeviceConfigurationProfileScopeJssUsers)
    jssUsers?: MobileDeviceConfigurationProfileScopeJssUsers[];

    @SpeakeasyMetadata()
    @Expose({ name: "limitations" })
    @Type(() => MobileDeviceConfigurationProfileScopeLimitations)
    limitations?: MobileDeviceConfigurationProfileScopeLimitations;

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeMobileDeviceGroups })
    @Expose({ name: "mobile_device_groups" })
    @Type(() => MobileDeviceConfigurationProfileScopeMobileDeviceGroups)
    mobileDeviceGroups?: MobileDeviceConfigurationProfileScopeMobileDeviceGroups[];

    @SpeakeasyMetadata({ elemType: MobileDeviceConfigurationProfileScopeMobileDevices })
    @Expose({ name: "mobile_devices" })
    @Type(() => MobileDeviceConfigurationProfileScopeMobileDevices)
    mobileDevices?: MobileDeviceConfigurationProfileScopeMobileDevices[];
}

export class MobileDeviceConfigurationProfileSelfServiceSecurityName extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "removal_disallowed" })
    removalDisallowed?: string;
}

export class MobileDeviceConfigurationProfileSelfServiceSelfServiceCategories extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "category" })
    @Type(() => Category)
    category?: Category;
}

export class MobileDeviceConfigurationProfileSelfServiceSelfServiceIcon extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "data" })
    data?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "filename" })
    filename?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "uri" })
    uri?: string;
}

export class MobileDeviceConfigurationProfileSelfService extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "feature_on_main_page" })
    featureOnMainPage?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "security_name" })
    @Type(() => MobileDeviceConfigurationProfileSelfServiceSecurityName)
    securityName?: MobileDeviceConfigurationProfileSelfServiceSecurityName;

    @SpeakeasyMetadata({
        elemType: MobileDeviceConfigurationProfileSelfServiceSelfServiceCategories,
    })
    @Expose({ name: "self_service_categories" })
    @Type(() => MobileDeviceConfigurationProfileSelfServiceSelfServiceCategories)
    selfServiceCategories?: MobileDeviceConfigurationProfileSelfServiceSelfServiceCategories[];

    @SpeakeasyMetadata()
    @Expose({ name: "self_service_description" })
    selfServiceDescription?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "self_service_icon" })
    @Type(() => MobileDeviceConfigurationProfileSelfServiceSelfServiceIcon)
    selfServiceIcon?: MobileDeviceConfigurationProfileSelfServiceSelfServiceIcon;
}

/**
 * OK
 */
export class MobileDeviceConfigurationProfile extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "general" })
    @Type(() => MobileDeviceConfigurationProfileGeneral)
    general?: MobileDeviceConfigurationProfileGeneral;

    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    @Type(() => MobileDeviceConfigurationProfileScope)
    scope?: MobileDeviceConfigurationProfileScope;

    @SpeakeasyMetadata()
    @Expose({ name: "self_service" })
    @Type(() => MobileDeviceConfigurationProfileSelfService)
    selfService?: MobileDeviceConfigurationProfileSelfService;
}
