/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { Expose, Type } from "class-transformer";

export class PatchReportComputer extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class PatchReportComputers extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "computer" })
    @Type(() => PatchReportComputer)
    computer?: PatchReportComputer;

    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;
}

export class Version extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: PatchReportComputers })
    @Expose({ name: "computers" })
    @Type(() => PatchReportComputers)
    computers?: PatchReportComputers[];

    @SpeakeasyMetadata()
    @Expose({ name: "software_version" })
    softwareVersion?: string;
}

export class PatchReportVersions extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    @Type(() => Version)
    version?: Version;
}

export class PatchReport extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "patch_software_title_id" })
    patchSoftwareTitleId?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "total_computers" })
    totalComputers?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "total_versions" })
    totalVersions?: number;

    @SpeakeasyMetadata({ elemType: PatchReportVersions })
    @Expose({ name: "versions" })
    @Type(() => PatchReportVersions)
    versions?: PatchReportVersions[];
}
