/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { CategoryObject } from "./categoryobject";
import { IdName } from "./idname";
import { SiteObject } from "./siteobject";
import { Expose, Type } from "class-transformer";

export enum PolicySchemasAccountMaintenanceAction {
    Create = "Create",
    Reset = "Reset",
    Delete = "Delete",
    DisableFileVault = "DisableFileVault",
}

export class PolicyAccount extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "action" })
    action?: PolicySchemasAccountMaintenanceAction;

    @SpeakeasyMetadata()
    @Expose({ name: "admin" })
    admin?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "archive_home_directory" })
    archiveHomeDirectory?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "archive_home_directory_to" })
    archiveHomeDirectoryTo?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "filevault_enabled" })
    filevaultEnabled?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "home" })
    home?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "password" })
    password?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "picture" })
    picture?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "realname" })
    realname?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "username" })
    username?: string;
}

export class PolicyAccounts extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "account" })
    @Type(() => PolicyAccount)
    account?: PolicyAccount;

    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;
}

export class PolicyDirectoryBindings extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "binding" })
    @Type(() => IdName)
    binding?: IdName;

    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;
}

export enum PolicyAction {
    Specified = "specified",
    Random = "random",
    Reset = "reset",
    FileVaultEnable = "fileVaultEnable",
    FileVaultDisable = "fileVaultDisable",
}

export class ManagementAccount extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "action" })
    action?: PolicyAction;

    @SpeakeasyMetadata()
    @Expose({ name: "managed_password" })
    managedPassword?: string;

    /**
     * Only necessary when utilizing the random action
     */
    @SpeakeasyMetadata()
    @Expose({ name: "managed_password_length" })
    managedPasswordLength?: number;
}

export enum OfMode {
    Command = "command",
    None = "none",
}

export class OpenFirmwareEfiPassword extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "of_mode" })
    ofMode?: OfMode;

    @SpeakeasyMetadata()
    @Expose({ name: "of_password" })
    ofPassword?: string;
}

export class AccountMaintenance extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: PolicyAccounts })
    @Expose({ name: "accounts" })
    @Type(() => PolicyAccounts)
    accounts?: PolicyAccounts[];

    @SpeakeasyMetadata({ elemType: PolicyDirectoryBindings })
    @Expose({ name: "directory_bindings" })
    @Type(() => PolicyDirectoryBindings)
    directoryBindings?: PolicyDirectoryBindings[];

    @SpeakeasyMetadata()
    @Expose({ name: "management_account" })
    @Type(() => ManagementAccount)
    managementAccount?: ManagementAccount;

    @SpeakeasyMetadata()
    @Expose({ name: "open_firmware_efi_password" })
    @Type(() => OpenFirmwareEfiPassword)
    openFirmwareEfiPassword?: OpenFirmwareEfiPassword;
}

export enum Action {
    Apply = "apply",
    Remediate = "remediate",
}

export enum RemediateKeyType {
    Individual = "Individual",
    Institutional = "Institutional",
    IndividualAndInstitutional = "Individual And Institutional",
}

export class DiskEncryption extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "action" })
    action?: Action;

    @SpeakeasyMetadata()
    @Expose({ name: "auth_restart" })
    authRestart?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "disk_encryption_configuration_id" })
    diskEncryptionConfigurationId?: number;

    /**
     * disk encryption ID to utilize for remediating institutional recovery key types.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "remediate_disk_encryption_configuration_id" })
    remediateDiskEncryptionConfigurationId?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "remediate_key_type" })
    remediateKeyType?: RemediateKeyType;
}

export enum PolicySchemasAction {
    AddToBeginning = "Add To Beginning",
    AddToEnd = "Add To End",
    Remove = "Remove",
}

export class PolicyDockItem extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "action" })
    action?: PolicySchemasAction;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class PolicyDockItems extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "dock_item" })
    @Type(() => PolicyDockItem)
    dockItem?: PolicyDockItem;

    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;
}

export class FilesProcesses extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "delete_file" })
    deleteFile?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "kill_process" })
    killProcess?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "locate_file" })
    locateFile?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "run_command" })
    runCommand?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "search_by_path" })
    searchByPath?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "search_for_process" })
    searchForProcess?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "spotlight_search" })
    spotlightSearch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "update_locate_database" })
    updateLocateDatabase?: boolean;
}

export enum Day {
    Sun = "Sun",
    Mon = "Mon",
    Tue = "Tue",
    Wed = "Wed",
    Thu = "Thu",
    Fri = "Fri",
    Sat = "Sat",
}

export class NoExecuteOn extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "day" })
    day?: Day;
}

export class DateTimeLimitations extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "activation_date" })
    activationDate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "activation_date_epoch" })
    activationDateEpoch?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "activation_date_utc" })
    activationDateUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "expiration_date" })
    expirationDate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "expiration_date_epoch" })
    expirationDateEpoch?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "expiration_date_utc" })
    expirationDateUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "no_execute_end" })
    noExecuteEnd?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "no_execute_on" })
    @Type(() => NoExecuteOn)
    noExecuteOn?: NoExecuteOn;

    @SpeakeasyMetadata()
    @Expose({ name: "no_execute_start" })
    noExecuteStart?: string;
}

export enum Frequency {
    OncePerComputer = "Once per computer",
    OncePerUserPerComputer = "Once per user per computer",
    OncePerUser = "Once per user",
    OnceEveryDay = "Once every day",
    OnceEveryWeek = "Once every week",
    OnceEveryMonth = "Once every month",
    Ongoing = "Ongoing",
}

export enum MinimumNetworkConnection {
    NoMinimum = "No Minimum",
    Ethernet = "Ethernet",
}

export class NetworkLimitations extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "any_ip_address" })
    anyIpAddress?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "minimum_network_connection" })
    minimumNetworkConnection?: MinimumNetworkConnection;
}

export enum NetworkRequirements {
    Any = "Any",
    Ethernet = "Ethernet",
}

export class OverrideDefaultSettings extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "distribution_point" })
    distributionPoint?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "force_afp_smb" })
    forceAfpSmb?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "sus" })
    sus?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "target_drive" })
    targetDrive?: string;
}

export enum RetryEvent {
    None = "none",
    Trigger = "trigger",
    CheckIn = "check-in",
}

export class PolicyGeneral extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "category" })
    @Type(() => CategoryObject)
    category?: CategoryObject;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_limitations" })
    @Type(() => DateTimeLimitations)
    dateTimeLimitations?: DateTimeLimitations;

    @SpeakeasyMetadata()
    @Expose({ name: "enabled" })
    enabled?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "frequency" })
    frequency?: Frequency;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "location_user_only" })
    locationUserOnly?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name: string;

    @SpeakeasyMetadata()
    @Expose({ name: "network_limitations" })
    @Type(() => NetworkLimitations)
    networkLimitations?: NetworkLimitations;

    @SpeakeasyMetadata()
    @Expose({ name: "network_requirements" })
    networkRequirements?: NetworkRequirements;

    @SpeakeasyMetadata()
    @Expose({ name: "notify_on_each_failed_retry" })
    notifyOnEachFailedRetry?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "offline" })
    offline?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "override_default_settings" })
    @Type(() => OverrideDefaultSettings)
    overrideDefaultSettings?: OverrideDefaultSettings;

    @SpeakeasyMetadata()
    @Expose({ name: "retry_attempts" })
    retryAttempts?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "retry_event" })
    retryEvent?: RetryEvent;

    @SpeakeasyMetadata()
    @Expose({ name: "site" })
    @Type(() => SiteObject)
    site?: SiteObject;

    @SpeakeasyMetadata()
    @Expose({ name: "target_drive" })
    targetDrive?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "trigger" })
    trigger?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "trigger_checkin" })
    triggerCheckin?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "trigger_enrollment_complete" })
    triggerEnrollmentComplete?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "trigger_login" })
    triggerLogin?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "trigger_logout" })
    triggerLogout?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "trigger_network_state_changed" })
    triggerNetworkStateChanged?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "trigger_other" })
    triggerOther?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "trigger_startup" })
    triggerStartup?: boolean;
}

export class Maintenance extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "byhost" })
    byhost?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "heal" })
    heal?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "install_all_cached_packages" })
    installAllCachedPackages?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "permissions" })
    permissions?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "prebindings" })
    prebindings?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "recon" })
    recon?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "reset_name" })
    resetName?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "system_cache" })
    systemCache?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "user_cache" })
    userCache?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "verify" })
    verify?: boolean;
}

export enum PolicySchemasPackageConfigurationAction {
    Install = "Install",
    Cache = "Cache",
    InstallCached = "Install Cached",
}

export class PolicyPackage extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "action" })
    action?: PolicySchemasPackageConfigurationAction;

    @SpeakeasyMetadata()
    @Expose({ name: "feu" })
    feu?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "fut" })
    fut?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "update_autorun" })
    updateAutorun?: boolean;
}

export class PolicyPackages extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "package" })
    @Type(() => PolicyPackage)
    package?: PolicyPackage;

    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;
}

export class PackageConfiguration extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: PolicyPackages })
    @Expose({ name: "packages" })
    @Type(() => PolicyPackages)
    packages?: PolicyPackages[];
}

export enum PolicySchemasPrintersAction {
    Install = "install",
    Uninstall = "uninstall",
}

export class PolicyPrinter extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "action" })
    action?: PolicySchemasPrintersAction;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "make_default" })
    makeDefault?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class PolicyPrinters extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "leave_existing_default" })
    leaveExistingDefault?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "printer" })
    @Type(() => PolicyPrinter)
    printer?: PolicyPrinter;

    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;
}

export class PolicyBuildings extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "building" })
    @Type(() => IdName)
    building?: IdName;
}

export class PolicyComputerGroups extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "computer_group" })
    @Type(() => IdName)
    computerGroup?: IdName;
}

export class PolicyComputer extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Name of the computer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "udid" })
    udid?: string;
}

export class PolicyComputers extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "computer" })
    @Type(() => PolicyComputer)
    computer?: PolicyComputer;
}

export class PolicyDepartments extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "department" })
    @Type(() => IdName)
    department?: IdName;
}

export class PolicySchemasBuildings extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "building" })
    @Type(() => IdName)
    building?: IdName;
}

export class PolicySchemasComputerGroups extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "computer_group" })
    @Type(() => IdName)
    computerGroup?: IdName;
}

export class PolicySchemasComputer extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Name of the computer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "udid" })
    udid?: string;
}

export class PolicySchemasComputers extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "computer" })
    @Type(() => PolicySchemasComputer)
    computer?: PolicySchemasComputer;
}

export class PolicySchemasDepartments extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "department" })
    @Type(() => IdName)
    department?: IdName;
}

export class PolicyIbeacons extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "ibeacon" })
    @Type(() => IdName)
    ibeacon?: IdName;
}

export class PolicyNetworkSegment extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Name of the network segment
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "uid" })
    uid?: string;
}

export class PolicyNetworkSegments extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "network_segment" })
    @Type(() => PolicyNetworkSegment)
    networkSegment?: PolicyNetworkSegment;
}

export class PolicyUserGroups extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user_group" })
    @Type(() => IdName)
    userGroup?: IdName;
}

export class PolicyUser extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class PolicyUsers extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user" })
    @Type(() => PolicyUser)
    user?: PolicyUser;
}

export class PolicyExclusions extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: PolicySchemasBuildings })
    @Expose({ name: "buildings" })
    @Type(() => PolicySchemasBuildings)
    buildings?: PolicySchemasBuildings[];

    @SpeakeasyMetadata({ elemType: PolicySchemasComputerGroups })
    @Expose({ name: "computer_groups" })
    @Type(() => PolicySchemasComputerGroups)
    computerGroups?: PolicySchemasComputerGroups[];

    @SpeakeasyMetadata({ elemType: PolicySchemasComputers })
    @Expose({ name: "computers" })
    @Type(() => PolicySchemasComputers)
    computers?: PolicySchemasComputers[];

    @SpeakeasyMetadata({ elemType: PolicySchemasDepartments })
    @Expose({ name: "departments" })
    @Type(() => PolicySchemasDepartments)
    departments?: PolicySchemasDepartments[];

    @SpeakeasyMetadata({ elemType: PolicyIbeacons })
    @Expose({ name: "ibeacons" })
    @Type(() => PolicyIbeacons)
    ibeacons?: PolicyIbeacons[];

    @SpeakeasyMetadata({ elemType: PolicyNetworkSegments })
    @Expose({ name: "network_segments" })
    @Type(() => PolicyNetworkSegments)
    networkSegments?: PolicyNetworkSegments[];

    @SpeakeasyMetadata({ elemType: PolicyUserGroups })
    @Expose({ name: "user_groups" })
    @Type(() => PolicyUserGroups)
    userGroups?: PolicyUserGroups[];

    @SpeakeasyMetadata({ elemType: PolicyUsers })
    @Expose({ name: "users" })
    @Type(() => PolicyUsers)
    users?: PolicyUsers[];
}

export class PolicySchemasUserGroups extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user_group" })
    userGroup?: string;
}

export class LimitToUsers extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: PolicySchemasUserGroups })
    @Expose({ name: "user_groups" })
    @Type(() => PolicySchemasUserGroups)
    userGroups?: PolicySchemasUserGroups[];
}

export class PolicySchemasIbeacons extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "ibeacon" })
    @Type(() => IdName)
    ibeacon?: IdName;
}

export class PolicySchemasNetworkSegments extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "network_segment" })
    @Type(() => IdName)
    networkSegment?: IdName;
}

export class PolicySchemasScopeUserGroups extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user_group" })
    @Type(() => IdName)
    userGroup?: IdName;
}

export class PolicySchemasUsers extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "user" })
    @Type(() => IdName)
    user?: IdName;
}

export class PolicyLimitations extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: PolicySchemasIbeacons })
    @Expose({ name: "ibeacons" })
    @Type(() => PolicySchemasIbeacons)
    ibeacons?: PolicySchemasIbeacons[];

    @SpeakeasyMetadata({ elemType: PolicySchemasNetworkSegments })
    @Expose({ name: "network_segments" })
    @Type(() => PolicySchemasNetworkSegments)
    networkSegments?: PolicySchemasNetworkSegments[];

    @SpeakeasyMetadata({ elemType: PolicySchemasScopeUserGroups })
    @Expose({ name: "user_groups" })
    @Type(() => PolicySchemasScopeUserGroups)
    userGroups?: PolicySchemasScopeUserGroups[];

    @SpeakeasyMetadata({ elemType: PolicySchemasUsers })
    @Expose({ name: "users" })
    @Type(() => PolicySchemasUsers)
    users?: PolicySchemasUsers[];
}

export class PolicyScope extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "all_computers" })
    allComputers?: boolean;

    @SpeakeasyMetadata({ elemType: PolicyBuildings })
    @Expose({ name: "buildings" })
    @Type(() => PolicyBuildings)
    buildings?: PolicyBuildings[];

    @SpeakeasyMetadata({ elemType: PolicyComputerGroups })
    @Expose({ name: "computer_groups" })
    @Type(() => PolicyComputerGroups)
    computerGroups?: PolicyComputerGroups[];

    @SpeakeasyMetadata({ elemType: PolicyComputers })
    @Expose({ name: "computers" })
    @Type(() => PolicyComputers)
    computers?: PolicyComputers[];

    @SpeakeasyMetadata({ elemType: PolicyDepartments })
    @Expose({ name: "departments" })
    @Type(() => PolicyDepartments)
    departments?: PolicyDepartments[];

    @SpeakeasyMetadata()
    @Expose({ name: "exclusions" })
    @Type(() => PolicyExclusions)
    exclusions?: PolicyExclusions;

    @SpeakeasyMetadata()
    @Expose({ name: "limit_to_users" })
    @Type(() => LimitToUsers)
    limitToUsers?: LimitToUsers;

    @SpeakeasyMetadata()
    @Expose({ name: "limitations" })
    @Type(() => PolicyLimitations)
    limitations?: PolicyLimitations;
}

export enum PolicyPriority {
    Before = "Before",
    After = "After",
}

export class PolicyScript extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "parameter10" })
    parameter10?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "parameter11" })
    parameter11?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "parameter4" })
    parameter4?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "parameter5" })
    parameter5?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "parameter6" })
    parameter6?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "parameter7" })
    parameter7?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "parameter8" })
    parameter8?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "parameter9" })
    parameter9?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "priority" })
    priority?: PolicyPriority;
}

export class PolicyScripts extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: PolicyScript })
    @Expose({ name: "script" })
    @Type(() => PolicyScript)
    script?: PolicyScript[];

    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;
}

export class PolicyCategory extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "display_in" })
    displayIn?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "feature_in" })
    featureIn?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class PolicySelfServiceCategories extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "category" })
    @Type(() => PolicyCategory)
    category?: PolicyCategory;
}

export class PolicySelfServiceIcon extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "filename" })
    filename?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "uri" })
    uri?: string;
}

export class PolicySelfService extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "feature_on_main_page" })
    featureOnMainPage?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "force_users_to_view_description" })
    forceUsersToViewDescription?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "install_button_text" })
    installButtonText?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "re-install_button_text" })
    reInstallButtonText?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "self_service_categories" })
    @Type(() => PolicySelfServiceCategories)
    selfServiceCategories?: PolicySelfServiceCategories;

    @SpeakeasyMetadata()
    @Expose({ name: "self_service_description" })
    selfServiceDescription?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "self_service_display_name" })
    selfServiceDisplayName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "self_service_icon" })
    @Type(() => PolicySelfServiceIcon)
    selfServiceIcon?: PolicySelfServiceIcon;

    @SpeakeasyMetadata()
    @Expose({ name: "use_for_self_service" })
    useForSelfService?: boolean;
}

export class PolicyUserInteraction extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "allow_deferral_minutes" })
    allowDeferralMinutes?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "allow_deferral_until_utc" })
    allowDeferralUntilUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "allow_user_to_defer" })
    allowUserToDefer?: boolean;

    @SpeakeasyMetadata()
    @Expose({ name: "message_finish" })
    messageFinish?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "message_start" })
    messageStart?: string;
}

export class Policy extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "account_maintenance" })
    @Type(() => AccountMaintenance)
    accountMaintenance?: AccountMaintenance;

    @SpeakeasyMetadata()
    @Expose({ name: "disk_encryption" })
    @Type(() => DiskEncryption)
    diskEncryption?: DiskEncryption;

    @SpeakeasyMetadata({ elemType: PolicyDockItems })
    @Expose({ name: "dock_items" })
    @Type(() => PolicyDockItems)
    dockItems?: PolicyDockItems[];

    @SpeakeasyMetadata()
    @Expose({ name: "files_processes" })
    @Type(() => FilesProcesses)
    filesProcesses?: FilesProcesses;

    @SpeakeasyMetadata()
    @Expose({ name: "general" })
    @Type(() => PolicyGeneral)
    general?: PolicyGeneral;

    @SpeakeasyMetadata()
    @Expose({ name: "maintenance" })
    @Type(() => Maintenance)
    maintenance?: Maintenance;

    @SpeakeasyMetadata()
    @Expose({ name: "package_configuration" })
    @Type(() => PackageConfiguration)
    packageConfiguration?: PackageConfiguration;

    @SpeakeasyMetadata({ elemType: PolicyPrinters })
    @Expose({ name: "printers" })
    @Type(() => PolicyPrinters)
    printers?: PolicyPrinters[];

    @SpeakeasyMetadata()
    @Expose({ name: "scope" })
    @Type(() => PolicyScope)
    scope?: PolicyScope;

    @SpeakeasyMetadata()
    @Expose({ name: "scripts" })
    @Type(() => PolicyScripts)
    scripts?: PolicyScripts;

    @SpeakeasyMetadata()
    @Expose({ name: "self_service" })
    @Type(() => PolicySelfService)
    selfService?: PolicySelfService;

    @SpeakeasyMetadata()
    @Expose({ name: "user_interaction" })
    @Type(() => PolicyUserInteraction)
    userInteraction?: PolicyUserInteraction;
}
