/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";

/**
 * Command to send device
 */
export enum CreateMobileDeviceCommandURLPathParamCommand {
    BlankPush = "BlankPush",
    ClearPasscode = "ClearPasscode",
    ClearRestrictionsPassword = "ClearRestrictionsPassword",
    DeviceLocation = "DeviceLocation",
    DisableLostMode = "DisableLostMode",
    EnableLostMode = "EnableLostMode",
    EraseDevice = "EraseDevice",
    PasscodeLockGracePeriod = "PasscodeLockGracePeriod",
    PlayLostModeSound = "PlayLostModeSound",
    RestartDevice = "RestartDevice",
    Settings = "Settings",
    SettingsDisableAppAnalytics = "SettingsDisableAppAnalytics",
    SettingsDisableBluetooth = "SettingsDisableBluetooth",
    SettingsEnablePersonalHotspot = "SettingsEnablePersonalHotspot",
    SettingsDisablePersonalHotspot = "SettingsDisablePersonalHotspot",
    SettingsDisableDataRoaming = "SettingsDisableDataRoaming",
    SettingsDisableDiagnosticSubmission = "SettingsDisableDiagnosticSubmission",
    SettingsDisableVoiceRoaming = "SettingsDisableVoiceRoaming",
    SettingsEnableAppAnalytics = "SettingsEnableAppAnalytics",
    SettingsEnableBluetooth = "SettingsEnableBluetooth",
    SettingsEnableDataRoaming = "SettingsEnableDataRoaming",
    SettingsEnableDiagnosticSubmission = "SettingsEnableDiagnosticSubmission",
    SettingsEnableVoiceRoaming = "SettingsEnableVoiceRoaming",
    ShutDownDevice = "ShutDownDevice",
    UnmanageDevice = "UnmanageDevice",
    UpdateInventory = "UpdateInventory",
}

export class CreateMobileDeviceCommandURLRequest extends SpeakeasyBase {
    /**
     * Command to send device
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=command" })
    command: CreateMobileDeviceCommandURLPathParamCommand;

    /**
     * Mobile device ID values, multiple IDs may be separated by commas (e.g. /id/13,14,15)
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=id_list" })
    idList: string;
}

export class CreateMobileDeviceCommandURLResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;
}
