/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class FindMobileDeviceHistoryByMacAddressRequest extends SpeakeasyBase {
    /**
     * Mac address to filter by
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=macaddress" })
    macaddress: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsFailedApp extends SpeakeasyBase {
    @SpeakeasyMetadata()
    managementStatus?: string;

    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsFailed extends SpeakeasyBase {
    @SpeakeasyMetadata()
    app?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsFailedApp;
}

export enum FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalledAppStoreFromMobileDeviceAppCatalogManagementStatus {
    Unmanaged = "Unmanaged",
    Managed = "Managed",
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalledAppStoreFromMobileDeviceAppCatalog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    bundleSize?: string;

    @SpeakeasyMetadata()
    dynamicSize?: string;

    @SpeakeasyMetadata()
    managementStatus?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalledAppStoreFromMobileDeviceAppCatalogManagementStatus;

    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    version?: string;
}

export enum FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalledInHouseFromMobileDeviceAppCatalogManagementStatus {
    Unmanaged = "Unmanaged",
    Managed = "Managed",
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalledInHouseFromMobileDeviceAppCatalog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    bundleSize?: string;

    @SpeakeasyMetadata()
    dynamicSize?: string;

    @SpeakeasyMetadata()
    managementStatus?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalledInHouseFromMobileDeviceAppCatalogManagementStatus;

    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    version?: string;
}

export enum FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalledOtherManagementStatus {
    Unmanaged = "Unmanaged",
    Managed = "Managed",
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalledOther extends SpeakeasyBase {
    @SpeakeasyMetadata()
    bundleSize?: string;

    @SpeakeasyMetadata()
    dynamicSize?: string;

    @SpeakeasyMetadata()
    managementStatus?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalledOtherManagementStatus;

    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalled extends SpeakeasyBase {
    @SpeakeasyMetadata()
    appStoreFromMobileDeviceAppCatalog?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalledAppStoreFromMobileDeviceAppCatalog;

    @SpeakeasyMetadata()
    inHouseFromMobileDeviceAppCatalog?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalledInHouseFromMobileDeviceAppCatalog;

    @SpeakeasyMetadata()
    other?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalledOther;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsPendingApp extends SpeakeasyBase {
    @SpeakeasyMetadata()
    managementStatus?: string;

    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsPending extends SpeakeasyBase {
    @SpeakeasyMetadata()
    app?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsPendingApp;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplications extends SpeakeasyBase {
    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsFailed,
    })
    failed?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsFailed[];

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalled,
    })
    installed?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsInstalled[];

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsPending,
    })
    pending?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplicationsPending[];
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLAuditsAudit extends SpeakeasyBase {
    @SpeakeasyMetadata()
    dateTime?: string;

    @SpeakeasyMetadata()
    dateTimeEpoch?: number;

    @SpeakeasyMetadata()
    event?: string;

    @SpeakeasyMetadata()
    username?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLAudits extends SpeakeasyBase {
    @SpeakeasyMetadata()
    audit?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLAuditsAudit;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksFailed extends SpeakeasyBase {
    @SpeakeasyMetadata()
    author?: string;

    @SpeakeasyMetadata()
    kind?: string;

    @SpeakeasyMetadata()
    managementStatus?: string;

    @SpeakeasyMetadata()
    title?: string;

    @SpeakeasyMetadata()
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksInstalledIbookstore extends SpeakeasyBase {
    @SpeakeasyMetadata()
    author?: string;

    @SpeakeasyMetadata()
    kind?: string;

    @SpeakeasyMetadata()
    managementStatus?: string;

    @SpeakeasyMetadata()
    title?: string;

    @SpeakeasyMetadata()
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksInstalledInhouse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    author?: string;

    @SpeakeasyMetadata()
    kind?: string;

    @SpeakeasyMetadata()
    managementStatus?: string;

    @SpeakeasyMetadata()
    title?: string;

    @SpeakeasyMetadata()
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksInstalled extends SpeakeasyBase {
    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksInstalledIbookstore,
    })
    ibookstore?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksInstalledIbookstore[];

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksInstalledInhouse,
    })
    inhouse?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksInstalledInhouse[];
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksPending extends SpeakeasyBase {
    @SpeakeasyMetadata()
    author?: string;

    @SpeakeasyMetadata()
    kind?: string;

    @SpeakeasyMetadata()
    managementStatus?: string;

    @SpeakeasyMetadata()
    title?: string;

    @SpeakeasyMetadata()
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooks extends SpeakeasyBase {
    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksFailed,
    })
    failed?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksFailed[];

    @SpeakeasyMetadata()
    installed?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksInstalled;

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksPending,
    })
    pending?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooksPending[];
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLGeneral extends SpeakeasyBase {
    @SpeakeasyMetadata()
    id?: number;

    @SpeakeasyMetadata()
    macAddress?: string;

    /**
     * Name of the device
     */
    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    serialNumber?: string;

    @SpeakeasyMetadata()
    udid?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsCompletedCommand extends SpeakeasyBase {
    @SpeakeasyMetadata()
    dateTimeCompleted?: string;

    @SpeakeasyMetadata()
    dateTimeCompletedEpoch?: number;

    @SpeakeasyMetadata()
    name?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsCompleted extends SpeakeasyBase {
    @SpeakeasyMetadata()
    command?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsCompletedCommand;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsFailedCommand extends SpeakeasyBase {
    @SpeakeasyMetadata()
    dateTimeFailed?: string;

    @SpeakeasyMetadata()
    dateTimeFailedEpoch?: number;

    @SpeakeasyMetadata()
    dateTimeIssued?: string;

    @SpeakeasyMetadata()
    dateTimeIssuedEpoch?: string;

    @SpeakeasyMetadata()
    error?: string;

    @SpeakeasyMetadata()
    name?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsFailed extends SpeakeasyBase {
    @SpeakeasyMetadata()
    command?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsFailedCommand;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsPendingCommand extends SpeakeasyBase {
    @SpeakeasyMetadata()
    dateTimeFailed?: string;

    @SpeakeasyMetadata()
    dateTimeFailedEpoch?: number;

    @SpeakeasyMetadata()
    dateTimeIssued?: string;

    @SpeakeasyMetadata()
    dateTimeIssuedEpoch?: string;

    @SpeakeasyMetadata()
    name?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsPending extends SpeakeasyBase {
    @SpeakeasyMetadata()
    command?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsPendingCommand;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommands extends SpeakeasyBase {
    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsCompleted,
    })
    completed?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsCompleted[];

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsFailed,
    })
    failed?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsFailed[];

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsPending,
    })
    pending?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommandsPending[];
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLUserLocationLocation extends SpeakeasyBase {
    @SpeakeasyMetadata()
    building?: string;

    @SpeakeasyMetadata()
    dateTime?: string;

    @SpeakeasyMetadata()
    dateTimeEpoch?: number;

    @SpeakeasyMetadata()
    department?: string;

    @SpeakeasyMetadata()
    emailAddress?: string;

    @SpeakeasyMetadata()
    fullName?: string;

    @SpeakeasyMetadata()
    phoneNumber?: string;

    @SpeakeasyMetadata()
    position?: string;

    @SpeakeasyMetadata()
    room?: string;

    @SpeakeasyMetadata()
    username?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationXMLUserLocation extends SpeakeasyBase {
    @SpeakeasyMetadata()
    location?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLUserLocationLocation;
}

/**
 * OK
 */
export class FindMobileDeviceHistoryByMacAddress200ApplicationXML extends SpeakeasyBase {
    @SpeakeasyMetadata()
    applications?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLApplications;

    @SpeakeasyMetadata({ elemType: FindMobileDeviceHistoryByMacAddress200ApplicationXMLAudits })
    audits?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLAudits[];

    @SpeakeasyMetadata()
    ebooks?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLEbooks;

    @SpeakeasyMetadata()
    general?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLGeneral;

    @SpeakeasyMetadata()
    managementCommands?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLManagementCommands;

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationXMLUserLocation,
    })
    userLocation?: FindMobileDeviceHistoryByMacAddress200ApplicationXMLUserLocation[];
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsFailedApp extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "management_status" })
    managementStatus?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsFailed extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "app" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsFailedApp)
    app?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsFailedApp;
}

export enum FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledAppStoreFromMobileDeviceAppCatalogManagementStatus {
    Unmanaged = "Unmanaged",
    Managed = "Managed",
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledAppStoreFromMobileDeviceAppCatalog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "bundle_size" })
    bundleSize?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "dynamic_size" })
    dynamicSize?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "management_status" })
    managementStatus?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledAppStoreFromMobileDeviceAppCatalogManagementStatus;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}

export enum FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledInHouseFromMobileDeviceAppCatalogManagementStatus {
    Unmanaged = "Unmanaged",
    Managed = "Managed",
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledInHouseFromMobileDeviceAppCatalog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "bundle_size" })
    bundleSize?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "dynamic_size" })
    dynamicSize?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "management_status" })
    managementStatus?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledInHouseFromMobileDeviceAppCatalogManagementStatus;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}

export enum FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledOtherManagementStatus {
    Unmanaged = "Unmanaged",
    Managed = "Managed",
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledOther extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "bundle_size" })
    bundleSize?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "dynamic_size" })
    dynamicSize?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "management_status" })
    managementStatus?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledOtherManagementStatus;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalled extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "app_store_from_mobile_device_app_catalog" })
    @Type(
        () =>
            FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledAppStoreFromMobileDeviceAppCatalog
    )
    appStoreFromMobileDeviceAppCatalog?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledAppStoreFromMobileDeviceAppCatalog;

    @SpeakeasyMetadata()
    @Expose({ name: "in_house_from_mobile_device_app_catalog" })
    @Type(
        () =>
            FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledInHouseFromMobileDeviceAppCatalog
    )
    inHouseFromMobileDeviceAppCatalog?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledInHouseFromMobileDeviceAppCatalog;

    @SpeakeasyMetadata()
    @Expose({ name: "other" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledOther)
    other?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalledOther;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsPendingApp extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "management_status" })
    managementStatus?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsPending extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "app" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsPendingApp)
    app?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsPendingApp;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplications extends SpeakeasyBase {
    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsFailed,
    })
    @Expose({ name: "failed" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsFailed)
    failed?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsFailed[];

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalled,
    })
    @Expose({ name: "installed" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalled)
    installed?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsInstalled[];

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsPending,
    })
    @Expose({ name: "pending" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsPending)
    pending?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplicationsPending[];
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONAuditsAudit extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "date_time" })
    dateTime?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_epoch" })
    dateTimeEpoch?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "event" })
    event?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "username" })
    username?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONAudits extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "audit" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONAuditsAudit)
    audit?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONAuditsAudit;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksFailed extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "author" })
    author?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "kind" })
    kind?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "management_status" })
    managementStatus?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksInstalledIbookstore extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "author" })
    author?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "kind" })
    kind?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "management_status" })
    managementStatus?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksInstalledInhouse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "author" })
    author?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "kind" })
    kind?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "management_status" })
    managementStatus?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksInstalled extends SpeakeasyBase {
    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksInstalledIbookstore,
    })
    @Expose({ name: "ibookstore" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksInstalledIbookstore)
    ibookstore?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksInstalledIbookstore[];

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksInstalledInhouse,
    })
    @Expose({ name: "inhouse" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksInstalledInhouse)
    inhouse?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksInstalledInhouse[];
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksPending extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "author" })
    author?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "kind" })
    kind?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "management_status" })
    managementStatus?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooks extends SpeakeasyBase {
    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksFailed,
    })
    @Expose({ name: "failed" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksFailed)
    failed?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksFailed[];

    @SpeakeasyMetadata()
    @Expose({ name: "installed" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksInstalled)
    installed?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksInstalled;

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksPending,
    })
    @Expose({ name: "pending" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksPending)
    pending?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooksPending[];
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONGeneral extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "mac_address" })
    macAddress?: string;

    /**
     * Name of the device
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "serial_number" })
    serialNumber?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "udid" })
    udid?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsCompletedCommand extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "date_time_completed" })
    dateTimeCompleted?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_completed_epoch" })
    dateTimeCompletedEpoch?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsCompleted extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "command" })
    @Type(
        () =>
            FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsCompletedCommand
    )
    command?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsCompletedCommand;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsFailedCommand extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "date_time_failed" })
    dateTimeFailed?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_failed_epoch" })
    dateTimeFailedEpoch?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_issued" })
    dateTimeIssued?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_issued_epoch" })
    dateTimeIssuedEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "error" })
    error?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsFailed extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "command" })
    @Type(
        () => FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsFailedCommand
    )
    command?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsFailedCommand;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsPendingCommand extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "date_time_failed" })
    dateTimeFailed?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_failed_epoch" })
    dateTimeFailedEpoch?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_issued" })
    dateTimeIssued?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_issued_epoch" })
    dateTimeIssuedEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsPending extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "command" })
    @Type(
        () => FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsPendingCommand
    )
    command?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsPendingCommand;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommands extends SpeakeasyBase {
    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsCompleted,
    })
    @Expose({ name: "completed" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsCompleted)
    completed?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsCompleted[];

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsFailed,
    })
    @Expose({ name: "failed" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsFailed)
    failed?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsFailed[];

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsPending,
    })
    @Expose({ name: "pending" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsPending)
    pending?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommandsPending[];
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONUserLocationLocation extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "building" })
    building?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time" })
    dateTime?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_epoch" })
    dateTimeEpoch?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "department" })
    department?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "email_address" })
    emailAddress?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "full_name" })
    fullName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "phone_number" })
    phoneNumber?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "position" })
    position?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "room" })
    room?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "username" })
    username?: string;
}

export class FindMobileDeviceHistoryByMacAddress200ApplicationJSONUserLocation extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "location" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONUserLocationLocation)
    location?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONUserLocationLocation;
}

/**
 * OK
 */
export class FindMobileDeviceHistoryByMacAddress200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "applications" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplications)
    applications?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONApplications;

    @SpeakeasyMetadata({ elemType: FindMobileDeviceHistoryByMacAddress200ApplicationJSONAudits })
    @Expose({ name: "audits" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONAudits)
    audits?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONAudits[];

    @SpeakeasyMetadata()
    @Expose({ name: "ebooks" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooks)
    ebooks?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONEbooks;

    @SpeakeasyMetadata()
    @Expose({ name: "general" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONGeneral)
    general?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONGeneral;

    @SpeakeasyMetadata()
    @Expose({ name: "management_commands" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommands)
    managementCommands?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONManagementCommands;

    @SpeakeasyMetadata({
        elemType: FindMobileDeviceHistoryByMacAddress200ApplicationJSONUserLocation,
    })
    @Expose({ name: "user_location" })
    @Type(() => FindMobileDeviceHistoryByMacAddress200ApplicationJSONUserLocation)
    userLocation?: FindMobileDeviceHistoryByMacAddress200ApplicationJSONUserLocation[];
}

export class FindMobileDeviceHistoryByMacAddressResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    body?: Uint8Array;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    findMobileDeviceHistoryByMacAddress200ApplicationJSONObject?: FindMobileDeviceHistoryByMacAddress200ApplicationJSON;
}
