/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class FindNetworkSegments200ApplicationXMLNetworkSegment extends SpeakeasyBase {
    @SpeakeasyMetadata()
    endingAddress?: string;

    @SpeakeasyMetadata()
    id?: number;

    /**
     * Name of the network segment
     */
    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    startingAddress?: string;
}

export class FindNetworkSegments200ApplicationXML extends SpeakeasyBase {
    @SpeakeasyMetadata()
    networkSegment?: FindNetworkSegments200ApplicationXMLNetworkSegment;

    @SpeakeasyMetadata()
    size?: number;
}

export class FindNetworkSegments200ApplicationJSONNetworkSegment extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "ending_address" })
    endingAddress?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    /**
     * Name of the network segment
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "starting_address" })
    startingAddress?: string;
}

export class FindNetworkSegments200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "network_segment" })
    @Type(() => FindNetworkSegments200ApplicationJSONNetworkSegment)
    networkSegment?: FindNetworkSegments200ApplicationJSONNetworkSegment;

    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;
}

export class FindNetworkSegmentsResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    body?: Uint8Array;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata({ elemType: FindNetworkSegments200ApplicationJSON })
    findNetworkSegments200ApplicationJSONObjects?: FindNetworkSegments200ApplicationJSON[];
}
