/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

export class FindPrinters200ApplicationXMLPrinter extends SpeakeasyBase {
    @SpeakeasyMetadata()
    id?: number;

    @SpeakeasyMetadata()
    name?: string;
}

export class FindPrinters200ApplicationXML extends SpeakeasyBase {
    @SpeakeasyMetadata()
    printer?: FindPrinters200ApplicationXMLPrinter;

    @SpeakeasyMetadata()
    size?: number;
}

export class FindPrinters200ApplicationJSONPrinter extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;
}

export class FindPrinters200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "printer" })
    @Type(() => FindPrinters200ApplicationJSONPrinter)
    printer?: FindPrinters200ApplicationJSONPrinter;

    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: number;
}

export class FindPrintersResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    body?: Uint8Array;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata({ elemType: FindPrinters200ApplicationJSON })
    findPrinters200ApplicationJSONObjects?: FindPrinters200ApplicationJSON[];
}
