/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose, Type } from "class-transformer";

/**
 * Subset to filter by
 */
export enum FindComputerHistoryByUDIDSubsetSubset {
    General = "General",
    ComputerUsageLogs = "ComputerUsageLogs",
    Audits = "Audits",
    PolicyLogs = "PolicyLogs",
    CasperRemoteLogs = "CasperRemoteLogs",
    ScreenSharingLogs = "ScreenSharingLogs",
    CasperImagingLogs = "CasperImagingLogs",
    Commands = "Commands",
    UserLocation = "UserLocation",
    MacAppStoreApplications = "MacAppStoreApplications",
}

export class FindComputerHistoryByUDIDSubsetRequest extends SpeakeasyBase {
    /**
     * Subset to filter by
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=subset" })
    subset: FindComputerHistoryByUDIDSubsetSubset;

    /**
     * Computer UDID to filter by
     */
    @SpeakeasyMetadata({ data: "pathParam, style=simple;explode=false;name=udid" })
    udid: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLAuditsAudit extends SpeakeasyBase {
    @SpeakeasyMetadata()
    dateTime?: string;

    @SpeakeasyMetadata()
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    event?: string;

    @SpeakeasyMetadata()
    username?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLAudits extends SpeakeasyBase {
    @SpeakeasyMetadata()
    audit?: FindComputerHistoryByUDIDSubset200ApplicationXMLAuditsAudit;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLCasperImagingLogsCasperImagingLog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    dateTime?: string;

    @SpeakeasyMetadata()
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    status?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLCasperImagingLogs extends SpeakeasyBase {
    @SpeakeasyMetadata()
    casperImagingLog?: FindComputerHistoryByUDIDSubset200ApplicationXMLCasperImagingLogsCasperImagingLog;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLCasperRemoteLogsCasperRemoteLog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    dateTime?: string;

    @SpeakeasyMetadata()
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    status?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLCasperRemoteLogs extends SpeakeasyBase {
    @SpeakeasyMetadata()
    casperRemoteLog?: FindComputerHistoryByUDIDSubset200ApplicationXMLCasperRemoteLogsCasperRemoteLog;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsCompletedCommand extends SpeakeasyBase {
    @SpeakeasyMetadata()
    completed?: string;

    @SpeakeasyMetadata()
    completedEpoch?: string;

    @SpeakeasyMetadata()
    completedUtc?: string;

    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    username?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsCompleted extends SpeakeasyBase {
    @SpeakeasyMetadata()
    command?: FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsCompletedCommand;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsFailedCommand extends SpeakeasyBase {
    @SpeakeasyMetadata()
    failed?: string;

    @SpeakeasyMetadata()
    failedEpoch?: string;

    @SpeakeasyMetadata()
    failedUtc?: string;

    @SpeakeasyMetadata()
    issued?: string;

    @SpeakeasyMetadata()
    issuedEpoch?: string;

    @SpeakeasyMetadata()
    issuedUtc?: string;

    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    status?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsFailed extends SpeakeasyBase {
    @SpeakeasyMetadata()
    command?: FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsFailedCommand;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsPendingCommand extends SpeakeasyBase {
    @SpeakeasyMetadata()
    issued?: string;

    @SpeakeasyMetadata()
    issuedEpoch?: string;

    @SpeakeasyMetadata()
    issuedUtc?: string;

    @SpeakeasyMetadata()
    lastPush?: string;

    @SpeakeasyMetadata()
    lastPushEpoch?: string;

    @SpeakeasyMetadata()
    lastPushUtc?: string;

    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    status?: string;

    @SpeakeasyMetadata()
    username?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsPending extends SpeakeasyBase {
    @SpeakeasyMetadata()
    command?: FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsPendingCommand;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLCommands extends SpeakeasyBase {
    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsCompleted,
    })
    completed?: FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsCompleted[];

    @SpeakeasyMetadata({ elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsFailed })
    failed?: FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsFailed[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsPending,
    })
    pending?: FindComputerHistoryByUDIDSubset200ApplicationXMLCommandsPending[];
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLComputerUsageLogsUsageLog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    dateTime?: string;

    @SpeakeasyMetadata()
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    event?: string;

    @SpeakeasyMetadata()
    username?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLComputerUsageLogs extends SpeakeasyBase {
    @SpeakeasyMetadata()
    usageLog?: FindComputerHistoryByUDIDSubset200ApplicationXMLComputerUsageLogsUsageLog;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLGeneral extends SpeakeasyBase {
    @SpeakeasyMetadata()
    id?: number;

    @SpeakeasyMetadata()
    macAddress?: string;

    /**
     * Name of the computer
     */
    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    serialNumber?: string;

    @SpeakeasyMetadata()
    udid?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsFailedApp extends SpeakeasyBase {
    @SpeakeasyMetadata()
    deployed?: string;

    @SpeakeasyMetadata()
    deployedEpoch?: number;

    @SpeakeasyMetadata()
    deployedUtc?: string;

    @SpeakeasyMetadata()
    lastUpdate?: string;

    @SpeakeasyMetadata()
    lastUpdateEpoch?: number;

    @SpeakeasyMetadata()
    lastUpdateUtc?: string;

    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    status?: string;

    @SpeakeasyMetadata()
    version?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsFailed extends SpeakeasyBase {
    @SpeakeasyMetadata()
    app?: FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsFailedApp;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsInstalledApp extends SpeakeasyBase {
    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    sizeMb?: string;

    @SpeakeasyMetadata()
    version?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsInstalled extends SpeakeasyBase {
    @SpeakeasyMetadata()
    app?: FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsInstalledApp;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsPendingApp extends SpeakeasyBase {
    @SpeakeasyMetadata()
    deployed?: string;

    @SpeakeasyMetadata()
    deployedEpoch?: number;

    @SpeakeasyMetadata()
    deployedUtc?: string;

    @SpeakeasyMetadata()
    lastUpdate?: string;

    @SpeakeasyMetadata()
    lastUpdateEpoch?: number;

    @SpeakeasyMetadata()
    lastUpdateUtc?: string;

    @SpeakeasyMetadata()
    name?: string;

    @SpeakeasyMetadata()
    version?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsPending extends SpeakeasyBase {
    @SpeakeasyMetadata()
    app?: FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsPendingApp;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplications extends SpeakeasyBase {
    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsFailed,
    })
    failed?: FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsFailed[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsInstalled,
    })
    installed?: FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsInstalled[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsPending,
    })
    pending?: FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplicationsPending[];
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLPolicyLogsPolicyLog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    dateTime?: string;

    @SpeakeasyMetadata()
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    policyId?: number;

    @SpeakeasyMetadata()
    policyName?: string;

    @SpeakeasyMetadata()
    status?: string;

    @SpeakeasyMetadata()
    username?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLPolicyLogs extends SpeakeasyBase {
    @SpeakeasyMetadata()
    policyLog?: FindComputerHistoryByUDIDSubset200ApplicationXMLPolicyLogsPolicyLog;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLScreenSharingLogsScreenSharingLog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    dateTime?: string;

    @SpeakeasyMetadata()
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    details?: string;

    @SpeakeasyMetadata()
    status?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLScreenSharingLogs extends SpeakeasyBase {
    @SpeakeasyMetadata()
    screenSharingLog?: FindComputerHistoryByUDIDSubset200ApplicationXMLScreenSharingLogsScreenSharingLog;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLUserLocationLocation extends SpeakeasyBase {
    @SpeakeasyMetadata()
    building?: string;

    @SpeakeasyMetadata()
    dateTime?: string;

    @SpeakeasyMetadata()
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    department?: string;

    @SpeakeasyMetadata()
    emailAddress?: string;

    @SpeakeasyMetadata()
    fullName?: string;

    @SpeakeasyMetadata()
    phoneNumber?: string;

    @SpeakeasyMetadata()
    position?: string;

    @SpeakeasyMetadata()
    room?: string;

    @SpeakeasyMetadata()
    username?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationXMLUserLocation extends SpeakeasyBase {
    @SpeakeasyMetadata()
    location?: FindComputerHistoryByUDIDSubset200ApplicationXMLUserLocationLocation;
}

/**
 * OK
 */
export class FindComputerHistoryByUDIDSubset200ApplicationXML extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLAudits })
    audits?: FindComputerHistoryByUDIDSubset200ApplicationXMLAudits[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLCasperImagingLogs,
    })
    casperImagingLogs?: FindComputerHistoryByUDIDSubset200ApplicationXMLCasperImagingLogs[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLCasperRemoteLogs,
    })
    casperRemoteLogs?: FindComputerHistoryByUDIDSubset200ApplicationXMLCasperRemoteLogs[];

    @SpeakeasyMetadata()
    commands?: FindComputerHistoryByUDIDSubset200ApplicationXMLCommands;

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLComputerUsageLogs,
    })
    computerUsageLogs?: FindComputerHistoryByUDIDSubset200ApplicationXMLComputerUsageLogs[];

    @SpeakeasyMetadata()
    general?: FindComputerHistoryByUDIDSubset200ApplicationXMLGeneral;

    @SpeakeasyMetadata()
    macAppStoreApplications?: FindComputerHistoryByUDIDSubset200ApplicationXMLMacAppStoreApplications;

    @SpeakeasyMetadata({ elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLPolicyLogs })
    policyLogs?: FindComputerHistoryByUDIDSubset200ApplicationXMLPolicyLogs[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLScreenSharingLogs,
    })
    screenSharingLogs?: FindComputerHistoryByUDIDSubset200ApplicationXMLScreenSharingLogs[];

    @SpeakeasyMetadata({ elemType: FindComputerHistoryByUDIDSubset200ApplicationXMLUserLocation })
    userLocation?: FindComputerHistoryByUDIDSubset200ApplicationXMLUserLocation[];
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONAuditsAudit extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "date_time" })
    dateTime?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_epoch" })
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_utc" })
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "event" })
    event?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "username" })
    username?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONAudits extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "audit" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONAuditsAudit)
    audit?: FindComputerHistoryByUDIDSubset200ApplicationJSONAuditsAudit;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONCasperImagingLogsCasperImagingLog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "date_time" })
    dateTime?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_epoch" })
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_utc" })
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONCasperImagingLogs extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "casper_imaging_log" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONCasperImagingLogsCasperImagingLog)
    casperImagingLog?: FindComputerHistoryByUDIDSubset200ApplicationJSONCasperImagingLogsCasperImagingLog;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONCasperRemoteLogsCasperRemoteLog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "date_time" })
    dateTime?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_epoch" })
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_utc" })
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONCasperRemoteLogs extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "casper_remote_log" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONCasperRemoteLogsCasperRemoteLog)
    casperRemoteLog?: FindComputerHistoryByUDIDSubset200ApplicationJSONCasperRemoteLogsCasperRemoteLog;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsCompletedCommand extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "completed" })
    completed?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "completed_epoch" })
    completedEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "completed_utc" })
    completedUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "username" })
    username?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsCompleted extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "command" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsCompletedCommand)
    command?: FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsCompletedCommand;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsFailedCommand extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "failed" })
    failed?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "failed_epoch" })
    failedEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "failed_utc" })
    failedUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "issued" })
    issued?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "issued_epoch" })
    issuedEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "issued_utc" })
    issuedUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsFailed extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "command" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsFailedCommand)
    command?: FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsFailedCommand;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsPendingCommand extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "issued" })
    issued?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "issued_epoch" })
    issuedEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "issued_utc" })
    issuedUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "last_push" })
    lastPush?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "last_push_epoch" })
    lastPushEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "last_push_utc" })
    lastPushUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "username" })
    username?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsPending extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "command" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsPendingCommand)
    command?: FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsPendingCommand;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONCommands extends SpeakeasyBase {
    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsCompleted,
    })
    @Expose({ name: "completed" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsCompleted)
    completed?: FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsCompleted[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsFailed,
    })
    @Expose({ name: "failed" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsFailed)
    failed?: FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsFailed[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsPending,
    })
    @Expose({ name: "pending" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsPending)
    pending?: FindComputerHistoryByUDIDSubset200ApplicationJSONCommandsPending[];
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONComputerUsageLogsUsageLog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "date_time" })
    dateTime?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_epoch" })
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_utc" })
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "event" })
    event?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "username" })
    username?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONComputerUsageLogs extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "usage_log" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONComputerUsageLogsUsageLog)
    usageLog?: FindComputerHistoryByUDIDSubset200ApplicationJSONComputerUsageLogsUsageLog;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONGeneral extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "mac_address" })
    macAddress?: string;

    /**
     * Name of the computer
     */
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "serial_number" })
    serialNumber?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "udid" })
    udid?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsFailedApp extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "deployed" })
    deployed?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "deployed_epoch" })
    deployedEpoch?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "deployed_utc" })
    deployedUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "last_update" })
    lastUpdate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "last_update_epoch" })
    lastUpdateEpoch?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "last_update_utc" })
    lastUpdateUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsFailed extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "app" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsFailedApp)
    app?: FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsFailedApp;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsInstalledApp extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "size_mb" })
    sizeMb?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsInstalled extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "app" })
    @Type(
        () => FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsInstalledApp
    )
    app?: FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsInstalledApp;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsPendingApp extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "deployed" })
    deployed?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "deployed_epoch" })
    deployedEpoch?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "deployed_utc" })
    deployedUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "last_update" })
    lastUpdate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "last_update_epoch" })
    lastUpdateEpoch?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "last_update_utc" })
    lastUpdateUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "name" })
    name?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "version" })
    version?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsPending extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "app" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsPendingApp)
    app?: FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsPendingApp;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplications extends SpeakeasyBase {
    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsFailed,
    })
    @Expose({ name: "failed" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsFailed)
    failed?: FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsFailed[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsInstalled,
    })
    @Expose({ name: "installed" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsInstalled)
    installed?: FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsInstalled[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsPending,
    })
    @Expose({ name: "pending" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsPending)
    pending?: FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplicationsPending[];
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONPolicyLogsPolicyLog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "date_time" })
    dateTime?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_epoch" })
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_utc" })
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "policy_id" })
    policyId?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "policy_name" })
    policyName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "username" })
    username?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONPolicyLogs extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "policy_log" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONPolicyLogsPolicyLog)
    policyLog?: FindComputerHistoryByUDIDSubset200ApplicationJSONPolicyLogsPolicyLog;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONScreenSharingLogsScreenSharingLog extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "date_time" })
    dateTime?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_epoch" })
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_utc" })
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "details" })
    details?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONScreenSharingLogs extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "screen_sharing_log" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONScreenSharingLogsScreenSharingLog)
    screenSharingLog?: FindComputerHistoryByUDIDSubset200ApplicationJSONScreenSharingLogsScreenSharingLog;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONUserLocationLocation extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "building" })
    building?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time" })
    dateTime?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_epoch" })
    dateTimeEpoch?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "date_time_utc" })
    dateTimeUtc?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "department" })
    department?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "email_address" })
    emailAddress?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "full_name" })
    fullName?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "phone_number" })
    phoneNumber?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "position" })
    position?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "room" })
    room?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "username" })
    username?: string;
}

export class FindComputerHistoryByUDIDSubset200ApplicationJSONUserLocation extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "location" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONUserLocationLocation)
    location?: FindComputerHistoryByUDIDSubset200ApplicationJSONUserLocationLocation;
}

/**
 * OK
 */
export class FindComputerHistoryByUDIDSubset200ApplicationJSON extends SpeakeasyBase {
    @SpeakeasyMetadata({ elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONAudits })
    @Expose({ name: "audits" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONAudits)
    audits?: FindComputerHistoryByUDIDSubset200ApplicationJSONAudits[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONCasperImagingLogs,
    })
    @Expose({ name: "casper_imaging_logs" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONCasperImagingLogs)
    casperImagingLogs?: FindComputerHistoryByUDIDSubset200ApplicationJSONCasperImagingLogs[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONCasperRemoteLogs,
    })
    @Expose({ name: "casper_remote_logs" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONCasperRemoteLogs)
    casperRemoteLogs?: FindComputerHistoryByUDIDSubset200ApplicationJSONCasperRemoteLogs[];

    @SpeakeasyMetadata()
    @Expose({ name: "commands" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONCommands)
    commands?: FindComputerHistoryByUDIDSubset200ApplicationJSONCommands;

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONComputerUsageLogs,
    })
    @Expose({ name: "computer_usage_logs" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONComputerUsageLogs)
    computerUsageLogs?: FindComputerHistoryByUDIDSubset200ApplicationJSONComputerUsageLogs[];

    @SpeakeasyMetadata()
    @Expose({ name: "general" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONGeneral)
    general?: FindComputerHistoryByUDIDSubset200ApplicationJSONGeneral;

    @SpeakeasyMetadata()
    @Expose({ name: "mac_app_store_applications" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplications)
    macAppStoreApplications?: FindComputerHistoryByUDIDSubset200ApplicationJSONMacAppStoreApplications;

    @SpeakeasyMetadata({ elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONPolicyLogs })
    @Expose({ name: "policy_logs" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONPolicyLogs)
    policyLogs?: FindComputerHistoryByUDIDSubset200ApplicationJSONPolicyLogs[];

    @SpeakeasyMetadata({
        elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONScreenSharingLogs,
    })
    @Expose({ name: "screen_sharing_logs" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONScreenSharingLogs)
    screenSharingLogs?: FindComputerHistoryByUDIDSubset200ApplicationJSONScreenSharingLogs[];

    @SpeakeasyMetadata({ elemType: FindComputerHistoryByUDIDSubset200ApplicationJSONUserLocation })
    @Expose({ name: "user_location" })
    @Type(() => FindComputerHistoryByUDIDSubset200ApplicationJSONUserLocation)
    userLocation?: FindComputerHistoryByUDIDSubset200ApplicationJSONUserLocation[];
}

export class FindComputerHistoryByUDIDSubsetResponse extends SpeakeasyBase {
    @SpeakeasyMetadata()
    body?: Uint8Array;

    @SpeakeasyMetadata()
    contentType: string;

    @SpeakeasyMetadata()
    statusCode: number;

    @SpeakeasyMetadata()
    rawResponse?: AxiosResponse;

    /**
     * OK
     */
    @SpeakeasyMetadata()
    findComputerHistoryByUDIDSubset200ApplicationJSONObject?: FindComputerHistoryByUDIDSubset200ApplicationJSON;
}
